<?php
/*
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle    Tn=n(n+1)/2   1, 3, 6, 10, 15, ...
Pentagonal    Pn=n(3n−1)/2    1, 5, 12, 22, 35, ...
Hexagonal   Hn=n(2n−1)    1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
*/

$found = false;
// start looking after the question
$n = 286;
$t = 0;
while(!$found){
  $t = $n * ($n + 1) / 2;
  // use quadratic formula from 43, and use new forumla for Triangle and Hexagonal
  $p = (1 + sqrt((1 + (24 * $t)))) / 6;
  if($p == (int)$p){
    $h = (1 + sqrt((1 + (8 * $t)))) / 4;
    if($h == (int)$h){
      $found = true;
      echo "n = {$n} | {$t} - {$p} - {$h}\n";
    }
  }
  $n++;
  // visual progress of what n is
  echo $n . "\r";
}

